[platformio]
default_envs = desktop_preview

[env]
lib_deps =
    lvgl/lvgl@^8.4.0
build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -Iinclude

[env:esp32_2432s028r]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_speed = 460800
lib_deps =
    ${env.lib_deps}
    lovyan03/LovyanGFX@^1.2.7
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.5
build_flags =
    ${env.build_flags}
build_src_filter =
    +<ui.cpp>
    +<embedded_main.cpp>
    -<sim_main.cpp>

[env:desktop_preview]
platform = native
lib_deps =
    ${env.lib_deps}
    lvgl/lv_drivers@^8.3.0
build_flags =
    ${env.build_flags}
    -DLV_DRV_CONF_INCLUDE_SIMPLE
    -I/opt/homebrew/include
    -I/opt/homebrew/include/SDL2
    -L/opt/homebrew/lib
    -lSDL2
build_src_filter =
    +<ui.cpp>
    +<sim_main.cpp>
    -<embedded_main.cpp>
